alias dir='ls --color=auto --format=vertical -la'
export HISTSIZE=10000 HISTFILESIZE=100000
export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64
export PATH=$PATH:$JAVA_HOME/bin

export SIGMA_HOME=/home/sumo/.sigmakee
export ONTOLOGYPORTAL_GIT=/home/sumo/workspace
export CATALINA_OPTS="$CATALINA_OPTS -Xms500M -Xmx5000M" 
export CATALINA_HOME=/home/sumo/Programs/apache-tomcat-8.5.31
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

