/** This code is copyright Articulate Software (c) 2003.  Some portions
copyright Teknowledge (c) 2003 and reused under the terms of the GNU license.
This software is released under the GNU Public License <http://www.gnu.org/copyleft/gpl.html>.
Users of this code also consent, by use of this code, to credit Articulate Software
and Teknowledge in any writings, briefings, publications, presentations, or 
other representations of any software which incorporates, builds on, or uses this 
code.  Please cite the following article in any publication with references:

Pease, A., (2003). The Sigma Ontology Development Environment, 
in Working Notes of the IJCAI-2003 Workshop on Ontology and Distributed Systems,
August 9, Acapulco, Mexico.
*/

package com.articulate.sigma;

/** ***************************************************************
 * This interface mandates the method isLegalForDisplay, which
 * determines whether or the display of a givne SUO-KIF term will be
 * allowed the calling context.
 */
public interface DisplayFilter {


    /** ***************************************************************
     * Returns true if suoKifTerm may be displayed or included in the
     * particular UI text or other output generated by the DocGen
     * object dg.
     *
     * @param dg The DocGen object that will use this filter to
     * determine which terms should be displayed or otherwise included
     * in generated output
     *
     * @param suoKifTerm A term in the SUO-KIF representation
     * language, which could be an atomic constant, a variable, a
     * quoted character string, or a list
     *
     * @return true or false
     */
    public boolean isLegalForDisplay (DocGen dg, String suoKifTerm);

}

