name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - 'docker/sigma-ci/Dockerfile'
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - 'docker/sigma-ci/Dockerfile'

env:
  DEFAULT_DOCKER_ACCOUNT: apease

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set image account name
        env:
          DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "IMAGE_ACCOUNT=${DOCKER_ACCOUNT:-$DEFAULT_DOCKER_ACCOUNT}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/sigma-ci/Dockerfile
          push: ${{ github.event_name == 'push' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_ACCOUNT }}/sigma-ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
