(TeX-add-style-hook "eprover"
 (lambda ()
    (LaTeX-add-index-entries
     "SETHEO"
     "Otter"
     "SPASS"
     "Vampire"
     "xyzzy"
     "TPTP!language"
     "terms"
     "variables"
     "subterm"
     "equations"
     "literal"
     "ordering"
     "reduction ordering"
     "selection functions"
     "literal!eligible"
     "eligible for paramodulation|see{literal, eligible}"
     "eligible for resolution|see{literal, eligible}"
     "eligible literals|see{literal, eligible}"
     "SP@\\textbf{SP} (calculus)"
     "equality resolution"
     "superposition!inference rule"
     "simultaneous superposition"
     "equality factoring"
     "rewriting"
     "E (theorem prover)"
     "subsumption"
     "simplify-reflect"
     "tautology deletion"
     "equality
     resolution"
     "contextual literal
     cutting"
     "condensing"
     "clause
       splitting"
     "clause splitting"
     "DISCOUNT"
     "relevancy pruning"
     "SInE"
     "TPTP"
     "clausification"
     "equational definition"
     "interreduction"
     "proof procedure"
     "given clause"
     "term
  ordering"
     "literal!selection"
     "term ordering"
     "clause evaluation"
     "LOP"
     "PCL"
     "common options"
     "eground|texttt"
     "enormalizer|texttt"
     "e\\_ltb\\_runner|texttt"
     "batch processing"
     "batch specifications"
     "interactive queries"
     "e\\_axfilter|texttt"
     "GPL"
     "GNU General Public
    License"
     "LGPL"
     "GNU Lesser General Public License")
    (LaTeX-add-bibitems
     "Bachmair:personal-98"
     "BDP89"
     "BG94"
     "CL73"
     "Dershowitz:IJCAI-91"
     "DKS97"
     "DS94a"
     "DS94b"
     "DS96a"
     "ES:SAT-2004"
     "BHF96"
     "HJL:CADE-99"
     "HV:CADE-2011"
     "Mc94"
     "MILSGSM:JAR-97"
     "MMZZM:DAC-2001"
     "MW:JAR-97"
     "NN:RTA-93"
     "NW:SmallCNF-2001"
     "RV:IJCAR-2001"
     "RV:AICOM-2002"
     "Schulz:Diss-2000"
     "Schulz:KI-2001"
     "Schulz:FLAIRS-2002"
     "Schulz:AICOM-2002"
     "Schulz:IJCAR-2004"
     "E:WWW-04"
     "SS:CADE-2002"
     "SSCG:IJCAR-2006"
     "Sutcliffe:TPTP-WWW"
     "Tammet:JAR-97"
     "WABCEKTT:CADE-99"
     "Weidenbach:personal-99"
     "Weidenbach:SPASS-2001"
     "WGR96")
    (LaTeX-add-labels
     "sec:intro"
     "sec:start"
     "sec:calculus"
     "def:basics:inferences:selection"
     "def:basics:inferences:eligible"
     "def:basics:inferences:sp"
     ":secsine"
     "sec:cnf"
     "sec:eqdef"
     "sec:presat"
     "sec:procedure"
     "fig:procedure"
     "sec:options"
     "sec:options:heuristics"
     "sec:options:orderings"
     "sec:options:strategies"
     "sec:options:watchlist"
     "sec:options:learning"
     "sec:options:others"
     "sec:language"
     "sec:output"
     "sec:output:essentials"
     "sec:output:normal"
     "sec:output:lots"
     "fig:answers"
     "sec:output:results"
     "tab:opts"
     "sec:bsf"
     "fig:ltbspec"
     "sec:iq"
     "fig:lbtsession"
     "fig:axfilter")
    (TeX-add-symbols
     '("etalchar" 1))
    (TeX-run-style-hooks
     "url"
     "supertabular"
     "estyle"
     "makeidx"
     "latex2e"
     "rep10"
     "report")))

